[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
]

[[repos]]
repo = "local"
hooks = [
    { 
        id = "rustfmt",
        name = "run rustfmt",
        entry = "cargo",
        args = ["fmt", "--", "--check"],
        language = "system",
        files = "\\.rs$"
    },
    {
        id = "clippy",
        name = "run clippy",
        entry = "cargo",
        args = ["clippy"],
        language = "system",
        files = "\\.rs$",
        pass_filenames = false
    },
    {
        id = "enforce-warnings",
        name = "enforce warnings",
        entry = "bash",
        args = ["./hooks/ci/check_warnings.sh"],
        language = "system",
        files = "^src/main.rs$",
        pass_filenames = false
    }
]
