name: Build and Test

on:
    workflow_call:
        inputs:
            build-config:
                required: false
                type: string
                default: release
                description: "Build configuration [debug, release]"
            coverage:
                required: false
                type: boolean
                default: false
                description: "Run tests with coverage"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Rust Toolchain
              run: |-
                  rustup target add wasm32-unknown-unknown
                  rustup component add llvm-tools
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2
            - name: Install trunk
              run: |-
                  export PATH="$HOME/.cargo/bin:$PATH"
                  cargo install wasm-bindgen-cli
                  cargo install cargo-binstall
                  cargo binstall --force trunk -y
                  cargo install cargo-llvm-cov
            - name: Build project
              run: trunk build --frozen ${{ inputs.build-config == 'release' && '--release' || '' }}
            - name: Test project (Coverage)
              if: ${{ inputs.coverage == 'true' }}
              run: cargo llvm-cov test --lcov --output-path lcov.info
            - name: Test project
              if: ${{ inputs.coverage == 'false' }}
              run: cargo test
