on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                config: [debug, release]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Setup Rust Toolchain
              run: rustup target add wasm32-unknown-unknown
            - name: Rust Cache
              uses: Swatinem/rust-cache@v2
            - name: Install trunk
              run: |-
                  export PATH="$HOME/.cargo/bin:$PATH"
                  cargo install wasm-bindgen-cli
                  cargo install cargo-binstall
                  cargo binstall --force trunk -y
            - name: Build project
              run: trunk build ${{ matrix.config == 'release' && '--release' || '' }}
