name: Continuous Integration

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    build-and-test:
        strategy:
            fail-fast: false
            matrix:
                config: [debug, release]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup Toolchain
              uses: ./.github/actions/setup-toolchain

            - name: Build project
              run: trunk build --frozen ${{ matrix.config == 'release' && '--release' || '' }}

            - name: Test project (Coverage)
              run: cargo llvm-cov test --lcov --output-path lcov.info

            - name: Upload to Coveralls.io
              uses: coverallsapp/github-action@v2
              if: ${{ matrix.config == 'release' }}
