name: Deploy to GitHub Pages

on:
    push:
        branches: [main, deployment]
    workflow_dispatch:

jobs:
    build-and-test:
        uses: ./.github/workflows/build.yml
        with:
            build-config: release
            coverage: false
            public-url: ${{ github.event.repository.name }}

    repackage:
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - name: Download Build Artifact
              uses: actions/download-artifact@v8
              with:
                  name: build-${{ github.sha }}-release
                  path: dist/
            - name: Re-upload as Pages Artifact
              id: deployment
              uses: actions/upload-pages-artifact@v4
              with:
                  path: dist/

    deploy:
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: repackage
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
